### ISSUE TITLE
crashing while launching the cometchat

### ISSUE THREAD

**Issue by parijathar** [CometChat/xamarin-chat-sdk-android-demo#1]
12-10 19:10:04.379 E/AndroidRuntime(30507): FATAL EXCEPTION: main
12-10 19:10:04.379 E/AndroidRuntime(30507): Process: com.tripplewin.tripplewinews.TripplewinEWS, PID: 30507
12-10 19:10:04.379 E/AndroidRuntime(30507): java.lang.NoSuchFieldError: No field rel_adView of type I in class Lcometchat/inscripts/com/readyui/R$id; or its superclasses (declaration of 'cometchat.inscripts.com.readyui.R$id' appears in /data/app/com.tripplewin.tripplewinews.TripplewinEWS-kDtsHE6XNnQtDReYtKCntg==/base.apk!classes2.dex)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at activities.CometChatActivity.setupFields(CometChatActivity.java:712)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at activities.CometChatActivity.onCreate(CometChatActivity.java:149)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.Activity.performCreate(Activity.java:7149)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.Activity.performCreate(Activity.java:7140)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.os.Looper.loop(Looper.java:193)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at android.app.ActivityThread.main(ActivityThread.java:6863)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at java.lang.reflect.Method.invoke(Native Method)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
12-10 19:10:04.379 E/AndroidRuntime(30507): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Unhandled Exception:

Java.Lang.NoSuchFieldError: No field rel_adView of type I in class Lcometchat/inscripts/com/readyui/R$id; or its superclasses (declaration of 'cometchat.inscripts.com.readyui.R$id' appears in /data/app/com.tripplewin.tripplewinews.TripplewinEWS-kDtsHE6XNnQtDReYtKCntg==/base.apk!classes2.dex)

Thread finished: <Thread Pool> #11
The thread 0xb has exited with code 0 (0x0).
Thread finished: <Thread Pool> #14
The thread 0xe has exited with code 0 (0x0).

**Comment by jitvarpatil** [comment]
Hi @parijathar 

This issue is due to the conflicts in view ids in CometChatUI & your project. Your Project or Other libraries might be using "rel_adView" for some other purpose or with references hence the above conflict. Please make sure you remove or rename the reference of the other field form your project for the seamless working of CometChat.

Feel free to contact us for further queries.

**Comment by parijathar** [comment]
Thank you for replying. But, i don't think thats the issue. Its actually not creating the id of the 'rel_adView' (which is in comet chat ui) in the Resource.Designer.cs file.

**Comment by jitvarpatil** [comment]
Hi @parijathar 

We have changed the resource name in our new Package 7.26.0, This will resolve the conflict issue you were facing. 

Feel free to contact us if you have further queries.
